# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project_SOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project_SOS

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

pod 'Google-Mobile-Ads-SDK'

pod "SimpleMarkdownParser", '~> 0.5.3'

pod 'Kingfisher', '~> 4.1'

end
