# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project_SOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project_SOS

pod 'Firebase/Core', '~> 4.2.0'
pod 'Firebase/Database', '~> 4.2.0'
pod 'Firebase/Auth', '~> 4.2.0'
pod 'Firebase/Storage', '~> 4.2.0'

pod 'Google-Mobile-Ads-SDK', '~> 7.24.1'

pod "SimpleMarkdownParser", '~> 0.5.3'

pod 'Kingfisher', '~> 4.1'

end
